"""empty message

Revision ID: 03510ef4c9cc
Revises: 
Create Date: 2018-04-24 07:16:41.455505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03510ef4c9cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('auth0_id', sa.String(), nullable=False),
    sa.Column('stripe_id', sa.String(), nullable=True),
    sa.Column('clipper_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
