"""empty message

Revision ID: e4eefbca8b5f
Revises: 03510ef4c9cc
Create Date: 2018-04-24 17:54:17.776561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4eefbca8b5f'
down_revision = '03510ef4c9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('auth0_id', sa.String(), nullable=False),
    sa.Column('stripe_id', sa.String(), nullable=True),
    sa.Column('clipper_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('auth0_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stripe_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('clipper_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name='user_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
